<?php

function get_cities_array()
{
    return array(
        array('id' => 'adana', 'plakakodu' => '01', 'alankodu' => '322', 'iladi' => 'Adana'),
        array('id' => 'adiyaman', 'plakakodu' => '02', 'alankodu' => '416', 'iladi' => 'Adıyaman'),
        array('id' => 'afyonkarahisar', 'plakakodu' => '03', 'alankodu' => '272', 'iladi' => 'Afyonkarahisar'),
        array('id' => 'agri', 'plakakodu' => '04', 'alankodu' => '472', 'iladi' => 'Ağrı'),
        array('id' => 'amasya', 'plakakodu' => '05', 'alankodu' => '358', 'iladi' => 'Amasya'),
        array('id' => 'ankara', 'plakakodu' => '06', 'alankodu' => '312', 'iladi' => 'Ankara'),
        array('id' => 'antalya', 'plakakodu' => '07', 'alankodu' => '242', 'iladi' => 'Antalya'),
        array('id' => 'artvin', 'plakakodu' => '08', 'alankodu' => '466', 'iladi' => 'Artvin'),
        array('id' => 'aydin', 'plakakodu' => '09', 'alankodu' => '256', 'iladi' => 'Aydın'),
        array('id' => 'balikesir', 'plakakodu' => '10', 'alankodu' => '266', 'iladi' => 'Balıkesir'),
        array('id' => 'bilecik', 'plakakodu' => '11', 'alankodu' => '228', 'iladi' => 'Bilecik'),
        array('id' => 'bingol', 'plakakodu' => '12', 'alankodu' => '426', 'iladi' => 'Bingöl'),
        array('id' => 'bitlis', 'plakakodu' => '13', 'alankodu' => '434', 'iladi' => 'Bitlis'),
        array('id' => 'bolu', 'plakakodu' => '14', 'alankodu' => '374', 'iladi' => 'Bolu'),
        array('id' => 'burdur', 'plakakodu' => '15', 'alankodu' => '248', 'iladi' => 'Burdur'),
        array('id' => 'bursa', 'plakakodu' => '16', 'alankodu' => '224', 'iladi' => 'Bursa'),
        array('id' => 'canakkale', 'plakakodu' => '17', 'alankodu' => '286', 'iladi' => 'Çanakkale'),
        array('id' => 'cankiri', 'plakakodu' => '18', 'alankodu' => '376', 'iladi' => 'Çankırı'),
        array('id' => 'corum', 'plakakodu' => '19', 'alankodu' => '364', 'iladi' => 'Çorum'),
        array('id' => 'denizli', 'plakakodu' => '20', 'alankodu' => '258', 'iladi' => 'Denizli'),
        array('id' => 'diyarbakir', 'plakakodu' => '21', 'alankodu' => '412', 'iladi' => 'Diyarbakır'),
        array('id' => 'edirne', 'plakakodu' => '22', 'alankodu' => '284', 'iladi' => 'Edirne'),
        array('id' => 'elazig', 'plakakodu' => '23', 'alankodu' => '424', 'iladi' => 'Elazığ'),
        array('id' => 'erzincan', 'plakakodu' => '24', 'alankodu' => '446', 'iladi' => 'Erzincan'),
        array('id' => 'erzurum', 'plakakodu' => '25', 'alankodu' => '442', 'iladi' => 'Erzurum'),
        array('id' => 'eskisehir', 'plakakodu' => '26', 'alankodu' => '222', 'iladi' => 'Eskişehir'),
        array('id' => 'gaziantep', 'plakakodu' => '27', 'alankodu' => '342', 'iladi' => 'Gaziantep'),
        array('id' => 'giresun', 'plakakodu' => '28', 'alankodu' => '454', 'iladi' => 'Giresun'),
        array('id' => 'gumushane', 'plakakodu' => '29', 'alankodu' => '456', 'iladi' => 'Gümüşhane'),
        array('id' => 'hakkari', 'plakakodu' => '30', 'alankodu' => '438', 'iladi' => 'Hakkari'),
        array('id' => 'hatay', 'plakakodu' => '31', 'alankodu' => '326', 'iladi' => 'Hatay'),
        array('id' => 'isparta', 'plakakodu' => '32', 'alankodu' => '246', 'iladi' => 'Isparta'),
        array('id' => 'istanbul-asya', 'plakakodu' => '34', 'alankodu' => '216', 'iladi' => 'İstanbul (Asya)'),
        array('id' => 'istanbul-avrupa', 'plakakodu' => '34', 'alankodu' => '212', 'iladi' => 'İstanbul (Avrupa)'),
        array('id' => 'izmir', 'plakakodu' => '35', 'alankodu' => '232', 'iladi' => 'İzmir'),
        array('id' => 'kars', 'plakakodu' => '36', 'alankodu' => '474', 'iladi' => 'Kars'),
        array('id' => 'kastamonu', 'plakakodu' => '37', 'alankodu' => '366', 'iladi' => 'Kastamonu'),
        array('id' => 'kayseri', 'plakakodu' => '38', 'alankodu' => '352', 'iladi' => 'Kayseri'),
        array('id' => 'kirklareli', 'plakakodu' => '39', 'alankodu' => '288', 'iladi' => 'Kırklareli'),
        array('id' => 'kirsehir', 'plakakodu' => '40', 'alankodu' => '386', 'iladi' => 'Kırşehir'),
        array('id' => 'kocaeli', 'plakakodu' => '41', 'alankodu' => '262', 'iladi' => 'Kocaeli'),
        array('id' => 'konya', 'plakakodu' => '42', 'alankodu' => '332', 'iladi' => 'Konya'),
        array('id' => 'kutahya', 'plakakodu' => '43', 'alankodu' => '274', 'iladi' => 'Kütahya'),
        array('id' => 'malatya', 'plakakodu' => '44', 'alankodu' => '422', 'iladi' => 'Malatya'),
        array('id' => 'manisa', 'plakakodu' => '45', 'alankodu' => '236', 'iladi' => 'Manisa'),
        array('id' => 'kahramanmaras', 'plakakodu' => '46', 'alankodu' => '344', 'iladi' => 'Kahramanmaraş'),
        array('id' => 'mardin', 'plakakodu' => '47', 'alankodu' => '482', 'iladi' => 'Mardin'),
        array('id' => 'mugla', 'plakakodu' => '48', 'alankodu' => '252', 'iladi' => 'Muğla'),
        array('id' => 'mus', 'plakakodu' => '49', 'alankodu' => '436', 'iladi' => 'Muş'),
        array('id' => 'nevsehir', 'plakakodu' => '50', 'alankodu' => '384', 'iladi' => 'Nevşehir'),
        array('id' => 'nigde', 'plakakodu' => '51', 'alankodu' => '388', 'iladi' => 'Niğde'),
        array('id' => 'ordu', 'plakakodu' => '52', 'alankodu' => '452', 'iladi' => 'Ordu'),
        array('id' => 'rize', 'plakakodu' => '53', 'alankodu' => '464', 'iladi' => 'Rize'),
        array('id' => 'sakarya', 'plakakodu' => '54', 'alankodu' => '264', 'iladi' => 'Sakarya'),
        array('id' => 'samsun', 'plakakodu' => '55', 'alankodu' => '362', 'iladi' => 'Samsun'),
        array('id' => 'siirt', 'plakakodu' => '56', 'alankodu' => '484', 'iladi' => 'Siirt'),
        array('id' => 'sinop', 'plakakodu' => '57', 'alankodu' => '368', 'iladi' => 'Sinop'),
        array('id' => 'sivas', 'plakakodu' => '58', 'alankodu' => '346', 'iladi' => 'Sivas'),
        array('id' => 'tekirdag', 'plakakodu' => '59', 'alankodu' => '282', 'iladi' => 'Tekirdağ'),
        array('id' => 'tokat', 'plakakodu' => '60', 'alankodu' => '356', 'iladi' => 'Tokat'),
        array('id' => 'trabzon', 'plakakodu' => '61', 'alankodu' => '462', 'iladi' => 'Trabzon'),
        array('id' => 'tunceli', 'plakakodu' => '62', 'alankodu' => '428', 'iladi' => 'Tunceli'),
        array('id' => 'sanliurfa', 'plakakodu' => '63', 'alankodu' => '414', 'iladi' => 'Şanlıurfa'),
        array('id' => 'usak', 'plakakodu' => '64', 'alankodu' => '276', 'iladi' => 'Uşak'),
        array('id' => 'van', 'plakakodu' => '65', 'alankodu' => '432', 'iladi' => 'Van'),
        array('id' => 'yozgat', 'plakakodu' => '66', 'alankodu' => '354', 'iladi' => 'Yozgat'),
        array('id' => 'zonguldak', 'plakakodu' => '67', 'alankodu' => '372', 'iladi' => 'Zonguldak'),
        array('id' => 'aksaray', 'plakakodu' => '68', 'alankodu' => '382', 'iladi' => 'Aksaray'),
        array('id' => 'bayburt', 'plakakodu' => '69', 'alankodu' => '458', 'iladi' => 'Bayburt'),
        array('id' => 'karaman', 'plakakodu' => '70', 'alankodu' => '338', 'iladi' => 'Karaman'),
        array('id' => 'kirikkale', 'plakakodu' => '71', 'alankodu' => '318', 'iladi' => 'Kırıkkale'),
        array('id' => 'batman', 'plakakodu' => '72', 'alankodu' => '488', 'iladi' => 'Batman'),
        array('id' => 'sirnak', 'plakakodu' => '73', 'alankodu' => '486', 'iladi' => 'Şırnak'),
        array('id' => 'bartin', 'plakakodu' => '74', 'alankodu' => '378', 'iladi' => 'Bartın'),
        array('id' => 'ardahan', 'plakakodu' => '75', 'alankodu' => '478', 'iladi' => 'Ardahan'),
        array('id' => 'igdir', 'plakakodu' => '76', 'alankodu' => '476', 'iladi' => 'Iğdır'),
        array('id' => 'yalova', 'plakakodu' => '77', 'alankodu' => '226', 'iladi' => 'Yalova'),
        array('id' => 'karabuk', 'plakakodu' => '78', 'alankodu' => '370', 'iladi' => 'Karabük'),
        array('id' => 'kilis', 'plakakodu' => '79', 'alankodu' => '348', 'iladi' => 'Kilis'),
        array('id' => 'osmaniye', 'plakakodu' => '80', 'alankodu' => '328', 'iladi' => 'Osmaniye'),
        array('id' => 'duzce', 'plakakodu' => '81', 'alankodu' => '380', 'iladi' => 'Düzce')
    );
}

?>