
<select id="contact-list-select" class="selectpicker form-control" data-live-search="true" data-dropup-auto="false" data-width="100%" data-size="10" tabindex="-98">
    <option><?php echo __( 'Please select a country...' , 'map_popup' ); ?></option>
    <option value="AF">Afghanistan</option>
    <option value="AM">Armenia</option>
    <option value="AZ">Azerbaijan</option>
    <option value="BH">Bahrain</option>
    <option value="BD">Bangladesh</option>
    <option value="BT">Bhutan</option>
    <option value="IO">British Indian Ocean Territory</option>
    <option value="BN">Brunei Darussalam</option>
    <option value="KH">Cambodia</option>
    <option value="CN">China</option>
    <option value="CX">Christmas Island</option>
    <option value="CC">Cocos (Keeling) Islands</option>
    <option value="GE">Georgia</option>
    <option value="HK">Hong Kong</option>
    <option value="IN">India</option>
    <option value="ID">Indonesia</option>
    <option value="IR">Iran</option>
    <option value="IQ">Iraq</option>
    <option value="IL">Israel</option>
    <option value="JP">Japan</option>
    <option value="JO">Jordan</option>
    <option value="KZ">Kazakhstan</option>
    <option value="KP">Korea, Democratic People's Republic of</option>
    <option value="KR">Korea, Republic of</option>
    <option value="KW">Kuwait</option>
    <option value="KG">Kyrgyzstan</option>
    <option value="LA">Lao</option>
    <option value="LB">Lebanon</option>
    <option value="MY">Malaysia</option>
    <option value="MV">Maldives</option>
    <option value="MN">Mongolia</option>
    <option value="MM">Myanmar (Burma)</option>
    <option value="NP">Nepal</option>
    <option value="OM">Oman</option>
    <option value="PK">Pakistan</option>
    <option value="PH">Philippines</option>
    <option value="QA">Qatar</option>
    <option value="RU">Russian Federation</option>
    <option value="SA">Saudi Arabia</option>
    <option value="SG">Singapore</option>
    <option value="LK">Sri Lanka</option>
    <option value="SY">Syria</option>
    <option value="TW">Taiwan</option>
    <option value="TJ">Tajikistan</option>
    <option value="TH">Thailand</option>
    <option value="TP">East Timor</option>
    <option value="TM">Turkmenistan</option>
    <option value="AE">United Arab Emirates</option>
    <option value="UZ">Uzbekistan</option>
    <option value="VN">Vietnam</option>
    <option value="YE">Yemen</option>
</select>