
<select id="contact-list-select" class="selectpicker form-control" data-live-search="true" data-dropup-auto="false" data-width="100%" data-size="10" tabindex="-98">
    <option><?php echo __( 'Please select a country...' , 'map_popup' ); ?></option>
    <option value="DZ">Algeria</option>
    <option value="AO">Angola</option>
    <option value="BJ">Benin</option>
    <option value="BW">Botswana</option>
    <option value="BF">Burkina Faso</option>
    <option value="BI">Burundi</option>
    <option value="CM">Cameroon</option>
    <option value="CV">Cape Verde</option>
    <option value="CF">Central African Republic</option>
    <option value="TD">Chad</option>
    <option value="KM">Comoros</option>
    <option value="CG">Congo</option>
    <option value="CD">Congo, the Democratic Republic of the</option>
    <option value="DJ">Dijibouti</option>
    <option value="EG">Egypt</option>
    <option value="GQ">Equatorial Guinea</option>
    <option value="ER">Eritrea</option>
    <option value="ET">Ethiopia</option>
    <option value="GA">Gabon</option>
    <option value="GM">Gambia</option>
    <option value="GH">Ghana</option>
    <option value="GN">Guinea</option>
    <option value="GW">Guinea-Bissau</option>
    <option value="CI">Cote d'Ivoire (Ivory Coast)</option>
    <option value="KE">Kenya</option>
    <option value="LS">Lesotho</option>
    <option value="LR">Liberia</option>
    <option value="LY">Libya</option>
    <option value="MG">Madagascar</option>
    <option value="MW">Malawi</option>
    <option value="ML">Mali</option>
    <option value="MR">Mauritania</option>
    <option value="MU">Mauritius</option>
    <option value="YT">Mayotte</option>
    <option value="MA">Morocco</option>
    <option value="MZ">Mozambique</option>
    <option value="NA">Namibia</option>
    <option value="NE">Niger</option>
    <option value="NG">Nigeria</option>
    <option value="RE">Reunion</option>
    <option value="RW">Rwanda</option>
    <option value="ST">Sao Tome and Principe</option>
    <option value="SH">Saint Helena</option>
    <option value="SN">Senegal</option>
    <option value="SC">Seychelles</option>
    <option value="SL">Sierra Leone</option>
    <option value="SO">Somalia</option>
    <option value="ZA">South Africa</option>
    <option value="SS">South Sudan</option>
    <option value="SD">Sudan</option>
    <option value="SZ">Swaziland</option>
    <option value="TZ">Tanzania</option>
    <option value="TG">Togo</option>
    <option value="TN">Tunisia</option>
    <option value="UG">Uganda</option>
    <option value="EH">Western Sahara</option>
    <option value="ZM">Zambia</option>
    <option value="ZW">Zimbabwe</option>
</select>